/**
 * Domains blocked for restaurant-owner / business registration.
 * Customers and staff may still use personal email elsewhere in the app.
 */

/** Major free / consumer mailbox providers */
export const FREE_EMAIL_DOMAINS = new Set([
  "gmail.com",
  "googlemail.com",
  "yahoo.com",
  "yahoo.co.in",
  "yahoo.in",
  "yahoo.co.uk",
  "outlook.com",
  "hotmail.com",
  "hotmail.co.uk",
  "live.com",
  "msn.com",
  "icloud.com",
  "me.com",
  "mac.com",
  "aol.com",
  "proton.me",
  "protonmail.com",
  "pm.me",
  "mail.com",
  "gmx.com",
  "gmx.net",
  "yandex.com",
  "yandex.ru",
  "rediffmail.com",
  "zoho.com",
  "fastmail.com",
  "tutanota.com",
  "hey.com",
]);

/** Common disposable / temporary inbox providers */
export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "grr.la",
  "sharklasers.com",
  "10minutemail.com",
  "10minutemail.net",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "throwaway.email",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "trashmail.com",
  "trashmail.me",
  "getnada.com",
  "dispostable.com",
  "maildrop.cc",
  "fakeinbox.com",
  "mintemail.com",
  "emailondeck.com",
  "spamgourmet.com",
  "mailnesia.com",
  "mytemp.email",
  "tempail.com",
  "burnermail.io",
  "mailcatch.com",
  "mohmal.com",
  "dropmail.me",
  "inboxkitten.com",
  "mailpoof.com",
]);
