/** Single source for module UIs (POS still uses mockData snapshot). */

export const INITIAL_CATEGORIES = [
  {
    id: "cat-fast",
    name: "Fast Food",
    description: "Quick service plates",
    itemCount: 0,
  },
  {
    id: "cat-juice",
    name: "Juice",
    description: "Fresh pressed & blends",
    itemCount: 0,
  },
  {
    id: "cat-bev",
    name: "Beverages",
    description: "Coffee, tea, sodas",
    itemCount: 0,
  },
  {
    id: "cat-dessert",
    name: "Desserts",
    description: "Sweet finishes",
    itemCount: 0,
  },
];

/** Placeholder food images (external URLs — used in <img>, not next/image). */
const IMG = {
  burger:
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop",
  wrap: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&h=400&fit=crop",
  fries:
    "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&h=400&fit=crop",
  juice:
    "https://images.unsplash.com/photo-1622597467836-f3285d2137b7?w=600&h=400&fit=crop",
  green:
    "https://images.unsplash.com/photo-1613478223719-2eb800eea4db?w=600&h=400&fit=crop",
  coffee:
    "https://images.unsplash.com/photo-1461023058943-07fc16d8d5b4?w=600&h=400&fit=crop",
  cola: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&h=400&fit=crop",
  cake: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&h=400&fit=crop",
  cheese:
    "https://images.unsplash.com/photo-1533134242443-d4fd840716bc?w=600&h=400&fit=crop",
};

export const INITIAL_MENU_ITEMS = [
  {
    id: "mi-1",
    name: "Classic Smash Burger",
    categoryId: "cat-fast",
    categoryName: "Fast Food",
    price: 12.99,
    description: "Double patty, American cheese, house sauce, brioche.",
    status: "active",
    badge: "Popular",
    image: IMG.burger,
  },
  {
    id: "mi-2",
    name: "Crispy Chicken Wrap",
    categoryId: "cat-fast",
    categoryName: "Fast Food",
    price: 10.5,
    description: "Spicy mayo, slaw, flour tortilla.",
    status: "active",
    badge: null,
    image: IMG.wrap,
  },
  {
    id: "mi-3",
    name: "Truffle Parmesan Fries",
    categoryId: "cat-fast",
    categoryName: "Fast Food",
    price: 7.25,
    description: "Skin-on fries, truffle oil, parmesan.",
    status: "active",
    badge: null,
    image: IMG.fries,
  },
  {
    id: "mi-4",
    name: "Sunrise Orange Juice",
    categoryId: "cat-juice",
    categoryName: "Juice",
    price: 5.5,
    description: "Fresh squeezed Valencias.",
    status: "active",
    badge: "Fresh",
    image: IMG.juice,
  },
  {
    id: "mi-5",
    name: "Green Detox Blend",
    categoryId: "cat-juice",
    categoryName: "Juice",
    price: 6.75,
    description: "Kale, apple, cucumber, ginger.",
    status: "active",
    badge: null,
    image: IMG.green,
  },
  {
    id: "mi-6",
    name: "Iced Caramel Latte",
    categoryId: "cat-bev",
    categoryName: "Beverages",
    price: 5.95,
    description: "Espresso, cold milk, caramel swirl.",
    status: "active",
    badge: null,
    image: IMG.coffee,
  },
  {
    id: "mi-7",
    name: "Craft Cola",
    categoryId: "cat-bev",
    categoryName: "Beverages",
    price: 3.5,
    description: "Small-batch vanilla cola.",
    status: "inactive",
    badge: null,
    image: IMG.cola,
  },
  {
    id: "mi-8",
    name: "Chocolate Lava Cake",
    categoryId: "cat-dessert",
    categoryName: "Desserts",
    price: 8.99,
    description: "Warm centre, vanilla bean gelato.",
    status: "active",
    badge: "Chef pick",
    image: IMG.cake,
  },
  {
    id: "mi-9",
    name: "Berry Lemon Cheesecake",
    categoryId: "cat-dessert",
    categoryName: "Desserts",
    price: 9.25,
    description: "Biscuit base, seasonal berries.",
    status: "active",
    badge: null,
    image: IMG.cheese,
  },
];

export const INITIAL_RECIPES = [
  {
    id: "r-1",
    name: "Smash burger — line build",
    menuItemId: "mi-1",
    menuItemName: "Classic Smash Burger",
    ingredientsPreview: "Beef smash, brioche, cheese, sauce…",
    ingredients: [
      "Ground chuck 4oz ×2",
      "Brioche bun toasted",
      "American cheese",
      "House sauce",
      "Pickles",
    ],
    steps:
      "Smash patties on flat top. Season. Flip once. Cheese melt. Toast buns. Sauce both crowns. Stack and wrap.",
  },
  {
    id: "r-2",
    name: "Lava cake — pickup",
    menuItemId: "mi-8",
    menuItemName: "Chocolate Lava Cake",
    ingredientsPreview: "Chocolate, butter, eggs, gelato…",
    ingredients: [
      "Dark chocolate 70%",
      "Butter",
      "Eggs, sugar",
      "Vanilla gelato scoop",
    ],
    steps:
      "Bake ramekins 11 min from cold. Test jiggle. Plate with gelato. Ticket fire on order.",
  },
];

export const INITIAL_FLOOR_TABLES = [
  {
    id: "tbl-1",
    tableNumber: "T01",
    capacity: 2,
    status: "available",
    zone: "Window",
  },
  {
    id: "tbl-2",
    tableNumber: "T02",
    capacity: 4,
    status: "occupied",
    zone: "Main",
  },
  {
    id: "tbl-3",
    tableNumber: "T03",
    capacity: 4,
    status: "available",
    zone: "Main",
  },
  {
    id: "tbl-4",
    tableNumber: "T04",
    capacity: 6,
    status: "occupied",
    zone: "Patio",
  },
  {
    id: "tbl-5",
    tableNumber: "T05",
    capacity: 2,
    status: "available",
    zone: "Bar",
  },
];

export const INITIAL_RESERVATIONS = [
  {
    id: "res-1",
    customerName: "Chen Wei",
    phone: "+1 415 555 0201",
    date: "2026-03-30",
    time: "18:30",
    guests: 6,
    tableNumber: "T06",
    status: "confirmed",
    notes: "Anniversary · window if possible",
    createdAt: "2026-03-26T14:00:00.000Z",
    confirmedAt: "2026-03-26T16:20:00.000Z",
    completedAt: null,
    cancelledAt: null,
  },
  {
    id: "res-2",
    customerName: "Mia Nguyen",
    phone: "+1 510 555 0882",
    date: "2026-03-30",
    time: "19:00",
    guests: 2,
    tableNumber: "T01",
    status: "pending",
    notes: "",
    createdAt: "2026-03-29T09:15:00.000Z",
    confirmedAt: null,
    completedAt: null,
    cancelledAt: null,
  },
  {
    id: "res-3",
    customerName: "Raj Patel",
    phone: "+1 628 555 0144",
    date: "2026-03-31",
    time: "19:15",
    guests: 4,
    tableNumber: "T03",
    status: "confirmed",
    notes: "One high chair",
    createdAt: "2026-03-28T11:00:00.000Z",
    confirmedAt: "2026-03-28T11:45:00.000Z",
    completedAt: null,
    cancelledAt: null,
  },
  {
    id: "res-4",
    customerName: "Sofia Alvarez",
    phone: "+1 415 555 0331",
    date: "2026-03-29",
    time: "20:00",
    guests: 8,
    tableNumber: "T04",
    status: "cancelled",
    notes: "Party — cancelled by guest",
    createdAt: "2026-03-20T18:00:00.000Z",
    confirmedAt: "2026-03-21T10:00:00.000Z",
    completedAt: null,
    cancelledAt: "2026-03-27T08:30:00.000Z",
  },
  {
    id: "res-5",
    customerName: "James Okonkwo",
    phone: "+1 650 555 0199",
    date: "2026-04-01",
    time: "17:30",
    guests: 3,
    tableNumber: "T02",
    status: "pending",
    notes: "Business dinner",
    createdAt: "2026-03-29T20:00:00.000Z",
    confirmedAt: null,
    completedAt: null,
    cancelledAt: null,
  },
];

export const INITIAL_STAFF = [
  {
    id: "st-1",
    name: "Elena Rossi",
    role: "Manager",
    phone: "+1 415 555 0101",
    email: "elena@restaurant.demo",
    status: "active",
  },
  {
    id: "st-2",
    name: "Marcus Lee",
    role: "Waiter",
    phone: "+1 415 555 0102",
    email: "marcus@restaurant.demo",
    status: "active",
  },
  {
    id: "st-3",
    name: "Priya Shah",
    role: "Chef",
    phone: "+1 415 555 0103",
    email: "priya@restaurant.demo",
    status: "on-leave",
  },
];

export const INITIAL_INVENTORY_ITEMS = [
  {
    id: "inv-1",
    name: "Extra virgin olive oil",
    category: "Dry goods",
    quantity: 4,
    unit: "bottle",
    reorderLevel: 8,
    supplier: "Mediterranean Importers",
    notes: "",
  },
  {
    id: "inv-2",
    name: "Ribeye primal",
    category: "Meat",
    quantity: 12,
    unit: "kg",
    reorderLevel: 10,
    supplier: "Butcher Collective",
    notes: "",
  },
  {
    id: "inv-3",
    name: "Heirloom tomatoes",
    category: "Produce",
    quantity: 0,
    unit: "crate",
    reorderLevel: 6,
    supplier: "Green Valley Farm",
    notes: "Seasonal — check delivery Tue",
  },
  {
    id: "inv-4",
    name: "Parmigiano Reggiano",
    category: "Dairy",
    quantity: 3,
    unit: "wheel",
    reorderLevel: 4,
    supplier: "Artisan Cheese Co.",
    notes: "",
  },
  {
    id: "inv-5",
    name: "Sparkling water (cases)",
    category: "Beverages",
    quantity: 24,
    unit: "case",
    reorderLevel: 12,
    supplier: "",
    notes: "",
  },
];

export const INITIAL_INVENTORY_HISTORY = [
  {
    id: "ih-1",
    itemId: "inv-1",
    itemName: "Extra virgin olive oil",
    delta: -2,
    message: "Kitchen transfer",
    createdAt: "2026-03-28T14:22:00.000Z",
  },
  {
    id: "ih-2",
    itemId: "inv-3",
    itemName: "Heirloom tomatoes",
    delta: -6,
    message: "Service depletion",
    createdAt: "2026-03-29T09:10:00.000Z",
  },
  {
    id: "ih-3",
    itemId: "inv-2",
    itemName: "Ribeye primal",
    delta: 4,
    message: "Delivery received",
    createdAt: "2026-03-29T11:45:00.000Z",
  },
];

export const INITIAL_CUSTOMERS = [
  {
    id: "cu-1",
    name: "Sarah Martinez",
    phone: "+1 628 555 0142",
    email: "sarah.m@email.demo",
    visits: 12,
    lastVisit: "2026-03-22",
    notes: "Prefers window tables. Shellfish allergy.",
    orderHistory: [
      { id: "o-1", date: "2026-03-22", total: 186.4, items: "Branzino, wine" },
      { id: "o-2", date: "2026-02-14", total: 224.0, items: "Tasting menu" },
      { id: "o-3", date: "2026-01-05", total: 98.5, items: "Lunch · starters" },
    ],
  },
  {
    id: "cu-2",
    name: "Alex Kim",
    phone: "+1 510 555 0199",
    email: "alex.k@email.demo",
    visits: 4,
    lastVisit: "2026-03-18",
    notes: "",
    orderHistory: [
      { id: "o-4", date: "2026-03-18", total: 62.0, items: "Bar snacks" },
    ],
  },
  {
    id: "cu-3",
    name: "Jordan Pierce",
    phone: "+1 415 555 0177",
    email: "j.pierce@email.demo",
    visits: 28,
    lastVisit: "2026-03-26",
    notes: "VIP — corporate card on file",
    orderHistory: [
      { id: "o-5", date: "2026-03-26", total: 412.0, items: "Private room" },
      { id: "o-6", date: "2026-03-01", total: 156.0, items: "Dinner x2" },
    ],
  },
];
