import { ObjectId } from "mongodb";
import { getTokenFromRequest } from "@/lib/authCookies";
import { verifyToken } from "@/lib/jwt";
import clientPromise from "@/lib/mongodb";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

function superAdminOnly(request) {
  const token = getTokenFromRequest(request);
  const payload = token ? verifyToken(token) : null;
  if (!payload || payload.role !== "super_admin") return null;
  return payload;
}

function formatDate(value) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString("en-IN", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatAmount(amount, currency) {
  const code = String(currency || "INR").toUpperCase();
  const value = Number(amount || 0);
  return `${code} ${value.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

async function generateReceiptPdf(payment) {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4
  const width = page.getWidth();
  const height = page.getHeight();
  const margin = 44;
  let y = height - margin;

  const titleFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await doc.embedFont(StandardFonts.Helvetica);

  page.drawRectangle({
    x: margin,
    y: y - 26,
    width: width - margin * 2,
    height: 30,
    color: rgb(0.07, 0.5, 0.39),
  });
  page.drawText("PAYMENT RECEIPT", {
    x: margin + 10,
    y: y - 16,
    size: 14,
    font: titleFont,
    color: rgb(1, 1, 1),
  });

  y -= 50;
  const rows = [
    ["Invoice ID", payment.invoiceId ?? "-"],
    ["Payment ID", payment._id.toString()],
    ["Payment Type", payment.paymentType ?? "order"],
    ["Restaurant", payment.restaurantName ?? "-"],
    ["Admin Email", payment.adminEmail ?? "-"],
    ["Plan", payment.planName ?? payment.plan ?? "-"],
    ["Billing Cycle", payment.billingCycle ?? "-"],
    ["Amount", formatAmount(payment.amount, payment.currency)],
    ["Status", String(payment.status ?? "pending").toUpperCase()],
    ["Method", payment.method ?? "-"],
    ["Paid At", formatDate(payment.paidAt)],
    ["Created At", formatDate(payment.createdAt)],
  ];

  for (const [label, value] of rows) {
    if (y < 80) break;
    page.drawText(`${label}:`, {
      x: margin,
      y,
      size: 10.5,
      font: titleFont,
      color: rgb(0.2, 0.2, 0.2),
    });
    page.drawText(String(value), {
      x: margin + 130,
      y,
      size: 10.5,
      font: bodyFont,
      color: rgb(0.1, 0.1, 0.1),
    });
    y -= 22;
  }

  page.drawLine({
    start: { x: margin, y: 56 },
    end: { x: width - margin, y: 56 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });
  page.drawText("Generated by Restaurant Management System", {
    x: margin,
    y: 40,
    size: 9,
    font: bodyFont,
    color: rgb(0.45, 0.45, 0.45),
  });

  return doc.save();
}

export async function GET(request, { params }) {
  if (!superAdminOnly(request)) {
    return Response.json({ success: false, error: "Forbidden." }, { status: 403 });
  }

  const { id } = await params;
  let _id;
  try {
    _id = new ObjectId(id);
  } catch {
    return Response.json({ success: false, error: "Invalid payment ID." }, { status: 400 });
  }

  try {
    const client = await clientPromise;
    const db = client.db();
    const payment = await db.collection("payments").findOne({ _id });
    if (!payment) {
      return Response.json({ success: false, error: "Payment not found." }, { status: 404 });
    }

    const pdfBytes = await generateReceiptPdf(payment);
    const filename = `${String(payment.invoiceId ?? `receipt-${payment._id}`)}.pdf`;

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    console.error("GET payment receipt error:", error.message);
    return Response.json({ success: false, error: "Something went wrong." }, { status: 500 });
  }
}
